name: bc_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  google_mlkit_face_detection: ^0.10.0
  google_mlkit_text_recognition: ^0.13.0
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  image: ^4.3.0
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true